language: node_js
node_js:
  - 4.2.2
script:
  - npm start
deploy:
  provider: heroku
  api_key:
    secure: U2zJubvjHs2oTHLklVmmgCPHiWYmhKcvDV5sAd+iiM8hhI6Pc30MtqrmOWHc1U0sKkaMColY9wAorez51/3dBfMZeofoIA2rvUudP1RiptvDKNwtXD2x8G2oZRhsfHthbax03PpB5K4lNKjqEMFyZ/vDZRgmmbC6lr8RVXjfaRyv2Ru2UFTncmusZ9v57IFXq6UehIaa0cqLWqlw/KoUAuVIHiTOMdgmo6Va29xFFyu9/+LQ8pBRbR60hQhSOxPZguBPvysqYePUdWOVBgm5MKG8URf1NUIBMk0JSAw2jdNJzDVjgr+WjGIe4KYOSV+n5Ierg6N3Y0P0xekLfAxgewsOOou8tLRrfh3dn1PHnQblosffnmSHPciM5hq4xmtzRbN0Ts0ZAZz86XF3bgwaOBvM+PcpR7Zq2zAlVz+zk7bveXlPcovhDryPX0Mivl1GzfTNkL4OYnLexxuWjZIRsArHMmQcblEz6pGl44fcaNgwSQHq0/FObl1nX7Z3M3IwUKt+hZvDpKOEta8BghKiP7apI5AorZdpN/sf0eN75DgXINxD6NsQ0u/Ar9j3wHddMwI9Wk0J9USp1ONDiAZuxhUbfvSpns8teKz6kcHarpCXW8XQHmp1PNU5y/PWAtUMiBGKEePmOD3XdY8DcRw9qz2hyBbuv6eoHbfucwJaQgw=
  app: front-end-automation
  on:
    repo: stremann/front-end-automation